# Список всех публикаций
GET http://localhost:3000/api/articles HTTP/1.1

###

# Список популярных публикаций
GET http://localhost:3000/api/articles/popular?limit=5 HTTP/1.1

###

# Полная информация о публикации
GET http://localhost:3000/api/articles/qhLyIT HTTP/1.1

###

# Список категорий
GET http://localhost:3000/api/categories HTTP/1.1

###

# Список объявлений по id категории
GET http://localhost:3000/api/articles/category/1 HTTP/1.1

###

# Создание публикации
POST http://localhost:3000/api/articles HTTP/1.1
Content-Type: application/json

{
  "title": "Заголовок новой публикации",
  "announce": "Это анонс новой публикации",
  "fullText": "Полный текст новой публикации",
  "createdDate": "2021-01-02T10:25:17.897Z",
  "category": ["Программирование", "Путешествия"]
}

###

# Создание публикации с лишним полем
POST http://localhost:3000/api/articles HTTP/1.1
Content-Type: application/json

{
  "title": "Заголовок новой публикации",
  "announce": "Это анонс новой публикации",
  "fullText": "Полный текст новой публикации",
  "createdDate": "2021-01-02T10:25:17.897Z",
  "category": ["Программирование", "Путешествия"],
  "comments": "test test test"
}

###

# Редактирование публикации
PUT http://localhost:3000/api/articles/qhLyIT HTTP/1.1
Content-Type: application/json

{
  "title": "Отредактированный заголовок",
  "announce": "Отредактированный анонс",
  "fullText": "Отредактированный полный текст",
  "createdDate": "2021-01-02T10:25:17.897Z",
  "category": ["Велоспорт"]
}

###

# Удаление публикации
DELETE http://localhost:3000/api/articles/darbzQ HTTP/1.1

###

# Список комментариев публикации
GET http://localhost:3000/api/articles/_1werb/comments HTTP/1.1

###

# Удаление комментария
DELETE http://localhost:3000/api/articles/_1werb/comments/EOb-5l HTTP/1.1

###

# Добавление нового комментария
POST http://localhost:3000/api/articles/_1werb/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Это новый комментарий"
}

###

# Добавление нового комментария с лишним полем
POST http://localhost:3000/api/articles/_1werb/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Это новый комментарий",
  "id": "test"
}

###

# Поиск публикаций
GET http://localhost:3000/api/search?query=рок-музыканты HTTP/1.1

###

# Создание юзера
POST http://localhost:3000/api/user
Content-Type: application/json

{
  "email": "test1@ya.ru",
  "firstname": "Юзер",
  "lastname": "Второй",
  "password": "qwerty12345",
  "repeat": "qwerty12345",
  "avatar": "myphoto.jpg"
}

###

# Аутентификация юзера

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "test@ya.ru",
  "password": "qwerty12345"
}